### ISSUE TITLE
Support for deprecated Profile 2 MOS calls

### ISSUE THREAD

**Issue by ebuzzz** [nrkno/sofie-mos-connection#57]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

We are currently using the library to connect to a NCS which supports MOS 2.8 (the initial version), but also makes use of the deprecated profile2 calls like `roStoryDelete`, `roStoryMove`, `roStoryMoveMultiple`, etc.

I need to implement these methods, but are you interested in a pull request, or has a decision been made to not implement these calls in this library

**Comment by nytamin** [comment]
Hi! Sorry for the slow response.
We'd be happy to accept a PR adding those deprecated messages, we didn't include them in the first place simply because we hadn't had a use for them ourselves.

**Comment by nytamin** [comment]
This has now been fixed, in version `3.0.7`
