### ISSUE TITLE
Bug Report: objID strings are incorrectly converted to number

### ISSUE THREAD

**Issue by PeterC89** [nrkno/sofie-mos-connection#92]
### About me

This bug report is posted on behalf of the BBC

### Observed Behavior

When ingesting a rundown with MOS objID's that look like numbers `sofie-mos-connection` incorrectly converts them to a `number` type.
E.G:
`100.543210` becomes `100.54321`

I'm guessing that this is caused by the `nativeType: true` option for the parser, I'm not sure what impact changing it would have...
https://github.com/nrkno/sofie-mos-connection/blob/a87681fed13d3379c41c78cd487606aabbf48128/packages/helper/src/utils/Utils.ts#L13

### Expected Behavior

Data from a MOS device should remain of a valid type.

### Version

release51

### Severity / Impact

~~This is a significant blocker for us as our clip objIDs are numeric as above.~~
A workaround has been implemented so this is less urgent but still an issue.

**Comment by olzzon** [comment]
PR has been made for this fix:
https://github.com/nrkno/sofie-mos-connection/pull/101

**Comment by nytamin** [comment]
This should now be resolved as of version `v4.2.0-alpha.1`, please reopen this if any issues persists,
