### ISSUE TITLE
Bug Report: "Bad" status even when MOS connection is working

### ISSUE THREAD

**Issue by PascalViauRC** [nrkno/sofie-mos-connection#93]
### About me

This is posted on behalf of CBC/Radio-Canada.

### Observed Behavior

Using a iNews MOS Gateway, a "Bad" status appears with a "Primary not connected" message in the Sofie MOS GATEWAY settings, even if the MOS connection is working fine.

In [MosDevice.ts](https://github.com/nrkno/sofie-mos-connection/blob/master/packages/connector/src/MosDevice.ts), there is this function :
```
getConnectionStatus(): IMOSConnectionStatus {
	// TODO: Implement this
	return {
		PrimaryConnected: this._primaryConnection ? this._primaryConnection.connected : false,
		PrimaryStatus: '',
		SecondaryConnected: this._secondaryConnection ? this._secondaryConnection.connected : false,
		SecondaryStatus: '',
	}
}
```
When I look at the `this._primaryConnection` object, I see a `_connected` key instead of a `connected` key, so the function returns `PrimaryConnected: false`, which causes the "Bad" status. So the `this._primaryConnection` object seems different for iNews than for other NRCS.

### Expected Behavior

The status should be "Good". In the `getConnectionStatus()` function, if I change `this._primaryConnection.connected`  to `this._primaryConnection._connected` , the status changes to "Good".

### Version

Sofie Core 1.49.2, @mos-connection/connector 3.0.7

### Severity / Impact

We are in a testing phase and the mos connection is working even with a "Bad" status, so it's not urgent.

**Comment by nytamin** [comment]
Often when there is a problem with a connection, it is because the `<heartbeat>` messages aren't received properly on one of the tcp-connections.
In the `4.0.0` version released today, I [added some better textual descriptions ](https://github.com/nrkno/sofie-mos-connection/commit/23d9b161d597223ed750a61dc7d87bacec4def51#diff-f92cb0522cf202f44968b95fb2758953f505927e6ae21ec2729dc8fc14173921R895) on what's wrong when there is no connection. Please give that a go and that might give you a clue.

**Comment by PascalViauRC** [comment]
You're right, now with `4.0.0` version I have a clearer message `{"connected": false, "status":"No heartbeats on port upper"}` My status is back to "Bad", but the message is accurate since I do have errors in the logs with the heartbeat. I will investigate further to see why the heartbeat fails.

**Comment by PascalViauRC** [comment]
This bug report will probably be fixed with the feature request [94](https://github.com/nrkno/sofie-mos-connection/issues/94).

**Comment by nytamin** [comment]
closing this in favor of #94
